### ISSUE TITLE
RuntimeError: Could not run 'aten::_cat' with arguments from the 'QuantizedCPUTensorId' backend. 

### ISSUE THREAD

**Issue by SkylerZheng** [Laicheng0830/Pytorch_Model_Quantization#1]
When I tried to inference with the quantized model using your evaluate_model.py, this error arose. From your side, did you have this problem? What pytorch version are you using.

**Comment by Laicheng0830** [comment]
I used Pyporch1.9.0. I had this problem before because the model forward inference did not use torch.quantization.QuantStub() and torch.quantization.DeQuantStub(). You can refer [Passing a quantized Tensor into a non-quantized kernel](https://pytorch.org/docs/stable/quantization.html#common-errors)

**Comment by SkylerZheng** [comment]
I see. Have you tried other pytorch versions? I tried 1.9, but I encountered many issues, so I downgraded to 1.4, and now I met another problem. 1.4 does not support for LayerNorm quantization, I'm thinking to upgraded to 1.6 because layernorm is supported by 1.6.  If some operator quantizations are not supported by some pytorch version, what should we do?

**Comment by SkylerZheng** [comment]
i see. thanks a lot. BTW, when using 1.9, have you met the problem of "zero point out of range?"
